### ISSUE TITLE
Adding face coordinates makes textures load incorrectly or not at all

### ISSUE THREAD

**Issue by YomieI** [hexundev/100oj-modgen#1]
Because the JSON generator encases provided coordinates in quotation marks, 100%OJ loads applicable textures incorrectly.
For both `face_x` and `face_y`, added coordinates should be without quotation marks.
Instead of
```
   {
    "path": "units/kai_00_00",
    "face_x": "115",
    "face_y": "85"
   },
```
it should be
```
   {
    "path": "units/kai_00_00",
    "face_x": 115,
    "face_y": 85
   },
```

**Comment by hexundev** [comment]
Should be fixed now, thanks for the report!
